### ISSUE TITLE
CSS系列之禁止用户选中

### ISSUE THREAD

**Issue by yuanyuanbyte** [yuanyuanbyte/Blog#26]
代码实现如下：
```css
.unselectable {
    user-select: none;

    -moz-user-select: -moz-none;
    -khtml-user-select: none;
    -webkit-user-select: none;
    /*
      Introduced in IE 10.
      See http://ie.microsoft.com/testdrive/HTML5/msUserSelect/
    */
    -ms-user-select: none;
 }
```
